spring:
  datasource:
    url: jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

# Optional: H2 console
spring.h2.console.enabled: true
spring.h2.console.path: /h2
